from typing import List, Set
from models.track import Track
from ytmusicapi import YTMusic
import time


class PlaylistManager:

    def __init__(self, client: YTMusic):
        self._client = client

    def update_group_playlist(self, artist_name: str, tracks: List[Track]):
        playlist_id = self._get_or_create_playlist(artist_name)
        existing_video_ids = self._get_existing_video_ids(playlist_id)

        new_video_ids = []
        for track in tracks:
            if track.video_id not in existing_video_ids:
                new_video_ids.append(track.video_id)

        if new_video_ids:
            self._client.add_playlist_items(
                playlistId=playlist_id,
                videoIds=new_video_ids,
                duplicates="SKIP"
            )
            print(f"  Added {len(new_video_ids)} tracks to '{artist_name}'")
        else:
            print(f"  '{artist_name}' playlist is already up to date")

    def rebuild_new_playlist(self, artist_name: str, tracks: List[Track]):
        title = f"New_{artist_name.capitalize()}"

        # Delete existing playlist if it exists
        all_playlists = self._client.get_library_playlists(limit=100)
        for playlist in all_playlists:
            if playlist["title"] == title:
                self._client.delete_playlist(playlist["playlistId"])
                print(f"  Deleted existing playlist: {title}")
                time.sleep(2)
                break

        # Create fresh playlist
        new_id = self._client.create_playlist(
            title=title,
            description="Auto-generated by ytmusic-kpop-tool",
            privacy_status="PRIVATE"
        )
        time.sleep(2)

        # Deduplicate video IDs before adding
        new_video_ids = list({track.video_id for track in tracks if track.video_id})

        if new_video_ids:
            self._client.add_playlist_items(
                playlistId=new_id,
                videoIds=new_video_ids,
                duplicates="SKIP"
            )
            time.sleep(3)
            print(f"  Added {len(new_video_ids)} tracks to '{title}'")

    def _get_or_create_playlist(self, title: str) -> str:
        all_playlists = self._client.get_library_playlists(limit=100)
        for playlist in all_playlists:
            if playlist["title"].lower() == title.lower() and playlist.get("isEditable"):
                print(f"  Found existing playlist: {title}")
                return playlist["playlistId"]

        print(f"  Creating new playlist: {title}")
        new_id = self._client.create_playlist(
            title=title,
            description="Auto-generated playlist",
            privacy_status="PRIVATE"
        )
        time.sleep(2)
        return new_id

    def _get_existing_video_ids(self, playlist_id: str) -> Set[str]:
        playlist = self._client.get_playlist(playlist_id)
        tracks = playlist.get("tracks") or []
        return {track["videoId"] for track in tracks if track.get("videoId")}